# Generated by Django 4.2.6 on 2025-02-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile_delete_registereduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
