# Generated by Django 4.2.6 on 2025-02-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
